### PR TITLE
Arch Linux updates

### PR DESCRIPTION
**Pull request by lilyanatia**
* add 2019.08.01 and 2019.07.01 releases
* use HTTPS for downloads

### CODE REVIEW

**Comment by antonym** [comment]
We can probably just leave the latest one drop the older ones.  Also, I'd drop the https as not all mirrors provide https support.

**Comment by lilyanatia** [comment]
the configuration in boot.cfg doesn't use all mirrors. it just uses mirror.rackspace.com, which does support HTTPS.

**Comment by GlitchedAxiom** [comment]
Version 2019.06.01 which is the only option currently, is not available anymore at rackspace mirrors. Could you please add the newest 2019.09.01 version and merge this?

Thanks.

**Comment by antonym** [comment]
Pushed here: https://github.com/antonym/netboot.xyz/commit/5269f76b830378c9af9c71d9d90da3b154a29f8c

Closing out

**Pull request closed without merging**
