### PR TITLE
Release 2.0.2

### PR DESCRIPTION
**Pull request by antonym**
Contains Fixes for Windows, timeout for version checking, and several fixes for Deepin and Elementary.

### CODE REVIEW

**Comment by thelamer** [comment]
Found a bug in deepin

**Comment by antonym** [comment]
K, I’ll hold off.

**Comment by thelamer** [comment]
We would need to version bump again unless we don't care about pushing a new RC

**Comment by antonym** [comment]
I had a change to slip in too so just cherry-picked them into RC and we can go with those without a version change.

**Pull request merged**
