### PR TITLE
add pbs

### PR DESCRIPTION
**Pull request by gratuxri**

### CODE REVIEW

**Comment by antonym** [comment]
Thanks for the suggestion, refactored a bit and added it here: https://github.com/netbootxyz/netboot.xyz/commit/f3f8e19b0ca4987d538393fb9716ce8896a54497

**Comment by gratuxri** [comment]
Maybe it make sense to include Proxmox Mail Gateway (pmg) as well ;)

**Comment by antonym** [comment]
Yeah, I may do that next... I have not used it before but if the installer method is the same way, it should be easy enough to add.

**Comment by gratuxri** [comment]
installer method is the same

**Pull request closed without merging**
