### PR TITLE
Use bootloader_filename instead of site_name for bootloader filenames consistently

### LINKED ISSUE #1095: Inconsistent use of bootloader_filename and site_name
The templates have a setting for `bootloader_filename`, but in most places `site_name` is used instead. This causes some features to break if `site_name` and `bootloader_filename` aren't set to the same thing.

For example the `tftpmenu` items aren't loaded and the URLs on the index.html page doesn't work.

### PR DESCRIPTION
**Pull request by abh**
Fixes #1095

### CODE REVIEW

**Comment by abh** [comment]
I didn't change the template for the checksum file as that using site_name seemed like it might be intentionally different.

For these files the filename generated was already using `bootloader_filename` and the references I changed were to match the actual files.

**Comment by abh** [comment]
Uh, not sure what's expected here. Bad bot?

**Comment by abh** [comment]
ping @antonym

**Comment by guppy0130** [comment]
I've tried this patch and the following is an example diff in the outputted `index.html`:

```diff
         <tr>
        <td> DHCP-snponly </td>
-       <td> <a href="ipxe/netboot.chicago.inthemainfra.me-snponly.efi">netboot.chicago.inthemainfra.me-snponly.efi</a> </td>
+       <td> <a href="ipxe/netboot.xyz-snponly.efi">netboot.xyz-snponly.efi</a> </td>
        <td> EFI w/ Simple Network Protocol, only boots from device chained from </td>
     </tr>
```

which matches the contents of the `ipxe/` directory correctly:

```console
(netboot.xyz) nyang@omada:~/src/netboot.xyz$ ls buildout/ipxe/
netboot.chicago.inthemainfra.me-sha256-checksums.txt  netboot.xyz.dsk  netboot.xyz.efi  netboot.xyz.kpxe  netboot.xyz.lkrn  netboot.xyz.pdsk  netboot.xyz-snp.efi  netboot.xyz-snponly.efi  netboot.xyz-undionly.kpxe
```

where `netboot.chicago.inthemainfra.me` is the `site_name`. I think this PR is great as-is if the goal is to have valid links/references. could this get merged @antonym ?

**Review by antonym — APPROVED** [review]

**Comment by abh** [comment]
thanks @antonym :-)

**Pull request merged**
