### PR TITLE
Check for squash in key for lmde

### LINKED ISSUE #944: "Mint 19 Cinnamon" booted instead  of "Mint Live LDME"

### PR DESCRIPTION
**Pull request by antonym**
Fixes https://github.com/netbootxyz/netboot.xyz/issues/944

### CODE REVIEW

**Comment by vstavrinov** [comment]
Thanks You. 
When the menu:

https://boot.netboot.xyz/live-mint.ipxe

will be updated?

**Comment by antonym** [comment]
You can access it early before the release by loading the development endpoint via the utilities menu at the end of the list.  All changes in the development branch can be accessed there.

**Comment by vstavrinov** [comment]
Got error:

`Could not boot: No such file or directory`

**Comment by vstavrinov** [comment]
The version problem:

goto 20.2-boot

but 

:20-boot

label exists

**Comment by antonym** [comment]
Yup, reworking the code a bit to avoid that.

**Comment by antonym** [comment]
Latest seems to be working better on dev endpoint.

**Comment by vstavrinov** [comment]
Yes, it works. Thanks.

**Pull request merged**
