### PR TITLE
Add ubuntu 20.04

### PR DESCRIPTION
**Pull request by vincentaubert**

### CODE REVIEW

**Comment by adunivr** [comment]
myarmyservice.com

**Comment by adunivr** [comment]
https://myarmyservice.info

**Comment by adunivr** [comment]
https://xatover.com/index.html

**Comment by adunivr** [comment]
😻💯👍🌎🍗🍕🥙🌮🍜

**Review by antonym — CHANGES_REQUESTED** [review]
Please make PR to development branch, thanks!

**Comment by vincentaubert** [comment]
done

**Review by antonym — APPROVED** [review]

**Pull request merged**
