### PR TITLE
Generate a working EFI ISO image (#268)

### PR DESCRIPTION
**Pull request by patrakov**
Tested in KVM with OVMF.

### CODE REVIEW

**Comment by antonym** [comment]
Cool, will check it out this week when I get some free time, thanks!

**Comment by patrakov** [comment]
For the record, I have tested the result not only with KVM, but also on a real server hosted by [Bacloud](https://www.bacloud.com/), over IPMI virtual media redirection.

**Comment by antonym** [comment]
Merged these fixes in with another commit ( https://github.com/antonym/netboot.xyz/pull/345 ) as there were some tweaks that needed to be made to your instructions on Xenial.  Making sure I don't break too much stuff.  Thanks for your contrib and please test the disks and let me know if they work for you.  I tested them in Virtual Box with EFI boot and they seemed to boot fine.

**Comment by patrakov** [comment]
I have downloaded the EFI ISO from netboot.xyz site and verified that it works in KVM.

**Pull request closed without merging**
